### ISSUE TITLE
Known task todo

### ISSUE THREAD

**Issue by kertaskids** [kertaskids/Witch-Football#3]
- [x] Witch Prefab 
- [x] Skybox
- [x] Player 8 directions
- [x] CharacterStat isfull, empty, isavailable 
- [x] Goal
- [x] Spawn ball and character if fallen
- [x] Player get manna after tackling
- [x] Replace damageToGuard & HP from passive to active or simply replace it with armor. 
- [x] Cutscene for the witch
- [x] Match UI (Gameplay, Custcene, Winning Post Match)
- [x] Merge character into witch class

**Comment by kertaskids** [comment]
Skybox and 8 directions are finished

**Comment by kertaskids** [comment]
Fixing BallReleasing() bug

**Comment by kertaskids** [comment]
Fixing Spiky tile bug

**Comment by kertaskids** [comment]
Replace <= with empty, > with full

**Comment by kertaskids** [comment]
Goal movement

**Comment by kertaskids** [comment]
done: 
- CharacterStat isfull, empty, isavailable, clean the code
- Player get mannaf after tackling
- Spawn ball and character if fallen

**Comment by kertaskids** [comment]
- Fixing goalscored, stun duration, add controlallowed
- Goal is scored only when Math.state is Mathplaying
- Add stun duration if the player is fallen
- Add controlAllowed to witchController
- Remove stun duration in SetPlayersControl() 
- Player can control after goal to tackle and to gain manna

**Comment by kertaskids** [comment]
Doing: 
- Create init in pinup.cs so we can assign it to the playerHUD class to make cinematic efffect. palyer pinup need to chache a witchcontroller. 
- Control the cinematic border in PinUpController. 
- What if skill's delay is 0 but the duration is > 0 ?

**Comment by kertaskids** [comment]
delete tile texture task
